https://carlos.mendible.com/2019/02/10/kubernetes-mount-file-pod-with-configmap/

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  namespace: yeuthuongtheodau-afamily-vn
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      nodeSelector:
        microsite3: "yes"
      containers:
      - image: registry.admicro.vn/sysadmin/ads_nginx:1.12.2-modsecurity
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 443
          timeoutSeconds: 2
        name: nginx
        ports:
        - containerPort: 443
          hostPort: 8099
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          tcpSocket:
            port: 443
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /etc/nginx
          readOnly: true
          name: nginx-conf
        - mountPath: /etc/nginx/conf.d/yeuthuongtheodau.afamily.vn.conf
          name: yeuthuongtheodau-conf
        - mountPath: /etc/nginx/ssl/admicro.vn.crt
          name: ssl-cert
        - mountPath: /etc/nginx/ssl/admicro.vn.key
          name: ssl-key
        - mountPath: /var/log/nginx
          name: log
        - mountPath: /var/www/yeuthuongtheodau.afamily.vn
          name: data
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: yeuthuongtheodau-conf
        configMap:
          name: yeuthuongtheodau-conf
      - name: ssl-key
        configMap:
          name: ssl-key
      - name: ssl-cert
        configMap:
          name: ssl-cert
      - name: data
        hostPath:
          path: /data/web/yeuthuongtheodau.afamily.vn
      - name: log
        hostPath:
          path: /data/log/nginx